require('dotenv').config()
const express = require("express")
const bodyParser = require("body-parser")
const userController = require("./Controller/UserController")
const bookController = require("./Controller/BookController")

const app = express()
app.use(bodyParser.json())
app.use("/api/auth", userController)
app.use("/api/books", bookController)
app.listen(process.env.APP_PORT)
